# Generated by Django 5.1.7 on 2026-03-20 08:02

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=auctions.models.default_end_time),
        ),
    ]
